### ISSUE TITLE
can't access google

### ISSUE THREAD

**Issue by yetzi1975** [ashislaha/CarDetection-Keras#1]
i'm in mianland of china, and i can't access google to get the training set. is there any other place to download them? 
thanks

**Comment by ashislaha** [comment]
Okay. Let me check. I stored the data in my Google Drive and made it public. It should be accessible from anywhere. Thanks for your concern.

**Comment by ashislaha** [comment]
Can you try this : https://s3.ap-south-1.amazonaws.com/car-detection-images/Archive.zip ?
Share your email id , I will send the database if that is still not worked.

**Comment by yetzi1975** [comment]
sorry, it is also unaccessible for me...

wangye34@126.com
thanks

**Comment by ashislaha** [comment]
Okay. Let me check to mail you the data.

**Comment by ashislaha** [comment]
Mailed you.

**Comment by yetzi1975** [comment]
thanks a lot! I have received.
